namespace DotAgent.Core.Models;

/// <summary>
/// Represents a function call to be executed by the agent.
/// </summary>
[Serializable]
public class FunctionCall
{
    /// <summary>
    /// Gets or sets the name of the function to call.
    /// </summary>
    public required string Name { get; set; }

    /// <summary>
    /// Gets or sets the parameters for the function call in JSON format.
    /// </summary>
    public required string Parameters { get; set; }

    /// <summary>
    /// Gets or sets the unique identifier for the function call.
    /// </summary>
    public required string Id { get; set; }
}

/// <summary>
/// Represents the response generated by an agent, which can include a message, function calls, or an error.
/// </summary>
[Serializable]
public class GenerationResponse
{
    /// <summary>
    /// Gets or sets an array of function calls to be executed.
    /// </summary>
    public FunctionCall[] FunctionCalls { get; set; } = null!;

    /// <summary>
    /// Gets or sets the generated message.
    /// </summary>
    public string? Message { get; set; } = "";

    /// <summary>
    /// Gets or sets any error message encountered during generation.
    /// </summary>
    public string? Error { get; set; } = "";
}